default-lease-time 600;
max-lease-time 7200;
authoritative;

option domain-name "factory.unclass.subs";
option domain-name-servers 10.150.102.11;

subnet 10.150.71.0 netmask 255.255.255.0 {
    range 10.150.71.101 10.150.71.199;
    option routers 10.150.71.1;
    option subnet-mask 255.255.255.0;
    option domain-name-servers 10.150.102.11;
    option broadcast-address 10.150.71.255;
}

host CI-CON-HOST01 {
    fixed-address 10.150.71.30;
    # CI-CON-HOST01
    hardware ethernet 00:50:56:AB:ED:77;
}
